lib/codegen/codegen.js, lib/codegen/fromcto/rust/rustvisitor.js, test/codegen/__snapshots__/codegen.js.snap, test/codegen/fromcto/rust/rustvisitor.js, types/index.d.ts, types/lib/codegen/codegen.d.ts, types/lib/codegen/fromcto/rust/rustvisitor.d.ts
- <ONE> Adds rust visitor to codegen.
- <TWO> Update the codegen snapshot with rust snapshot so able to generate rust code.
- <THREE> Add support for scalar field.
- <FOUR> Replace single quotes with double quote for consistency and fix test against this change.
=> feat(): Add rust to codegen and support for scalar type

lib/codegen/fromcto/csharp/csharpvisitor.js, test/codegen/__snapshots__/codegen.js.snap, test/codegen/fromcto/csharp/csharpvisitor.js
The 'concerto.scalar.uuid' namespace is automatically added to the .NET models if the CTO file has a property of type UUID. However, since we treat UUID in CTO as 'System.Guid' in .NET, there is no need to add an import namespace to the generated .NET file.
Adding this namespace resulting in build failures in .NET, so update csharp codegen to ignore adding this namespace to .net models. So excluding the concerto scalar namespace in dotnet generated models.
=> fix(tools): Add dummy classes to dotnet gen models to avoid compilation errors

lib/codegen/fromJsonSchema/cto/jsonSchemaVisitor.js, test/codegen/fromJsonSchema/cto/data/jsonSchemaFromTypescriptShapes.json, test/codegen/fromJsonSchema/cto/jsonSchemaVisitor.js
Fixes bug when inferring Concerto from JSON Schema.
- URL-encoded references get decoded.
- References in definitions' bodies get handled.
=> fix(jsonschema): fix bug with inference from JSON Schema

lib/codegen/fromcto/csharp/csharpvisitor.js, lib/codegen/fromcto/jsonschema/jsonschemavisitor.js, package-lock.json, package.json, test/codegen/fromcto/csharp/csharpvisitor.js, test/codegen/fromcto/data/model/stringlength.cto, test/codegen/fromcto/jsonschema/jsonschemavisitor.js
- String length validation incorporated to csharp and json schema codegen module
- Issue #https://github.com/accordproject/concerto/issues/643
- Pull Request #https://github.com/accordproject/concerto/pull/647
=> feat(*): String length validation for csharp,json generators

lib/codegen/fromcto/csharp/csharpvisitor.js, test/codegen/fromcto/csharp/csharpvisitor.js
dotnet codegenerated models fail to compile when concept names conflict with dependent projects/namespaces.
Resolve parent type/property type with fully qualified name if its imported from different model/namespace
```
namespace org.acme.other@2.3.4
concept OtherThing {
o String id
}
```
```
namespace org.acme@1.2.3
import org.acme.other@2.3.4.{ OtherThing }
concept Thing extends OtherThing {
o String someid
}
concept ThingTwo {
o OtherThing otherThing
}
concept ThingThree extends Thing {
o String name
}
```
Should get translated csharp gen code like below (for readability, I removed few concerto annotations in this example)
```
namespace org.acme;
using org.acme.other;
using AccordProject.Concerto;
public class Thing : Concept {
public override string _class { get; } = …
```
=> fix(*):fix concept name conflict with dependent namespaces

lib/codegen/fromcto/csharp/csharpvisitor.js, test/codegen/fromcto/csharp/csharpvisitor.js
When pascalCase is set to true, fully qualified name of a property removes the separators like `.-_` is removed from fully qualified name of a property.
This is causing the problem when we try to use fqn for a property to avoid type conflicts as reported in this issue https://github.com/accordproject/concerto-codegen/issues/15
=> fix(*): pascal casing fix to resolve fqn

lib/codegen/fromcto/typescript/typescriptvisitor.js, test/codegen/__snapshots__/codegen.js.snap
- Do not include enums in the generated union types
- Do not prefix imports of enums with an `I`.
- <ONE>
- <TWO>
=> fix(typescript) do not create unions for enums and fix imports

lib/codegen/fromcto/mermaid/mermaidvisitor.js, test/codegen/__snapshots__/codegen.js.snap
More context here: https://github.com/accordproject/concerto/issues/649
- `visitRelationship` method from `MermaidVisitor` class was overriding the same method in `DiagramVisitor` class, which caused this issue.
- Changed `visitRelationship` from `MermaidVisitor` class to `writeRelationshipAggregation` method, which acts as helper method now create the relationship-aggregation line in mermaid diagram code.
- `MermaidVisitor` class no more has `visitRelationship` method, not sure if this would break the visitor pattern. Wanted to clarify if this is the correct approach.
- Issue  https://github.com/accordproject/concerto/issues/649
=> bug(lib): mermaid diagram bug solution

package.json
Fixes browser entry point in package.json to align with webpack config.
See https://github.com/accordproject/concerto-codegen/blob/e37980bf3458bb8597287899874c518963e49504/webpack.config.js#L28
- <ONE>
- <TWO>
- <ONE>
- <TWO>
=> fix(browser) : package.json bug

lib/codegen/fromcto/csharp/csharpvisitor.js, test/codegen/__snapshots__/codegen.js.snap, test/codegen/fromcto/csharp/csharpvisitor.js
- Remove ; from the property declaration for a field of type Map.
- Fix the indentation for map properties
=> fix(csharp):remove semicolon (;) from map property declaration

lib/codegen/fromcto/graphql/graphqlvisitor.js, test/codegen/__snapshots__/codegen.js.snap, test/codegen/fromcto/graphql/graphqlvisitor.js
```
type Map1 {
key: String
value: String
}
type Map2 {
key: String
value: DateTime
}
type Map3 {
key: String
value: SSN
}
type Map4 {
key: String
value: Concept
}
type Map5 {
key: SSN
value: String
}
type Map6 {
key: SSN
value: Employee
}
```
=> feat(map): Codegen for GraphQL Target

lib/codegen/fromcto/csharp/csharpvisitor.js, lib/codegen/fromcto/typescript/typescriptvisitor.js, lib/common/graph.js, package-lock.json, package.json, test/codegen/__snapshots__/codegen.js.snap, test/codegen/codegen.js, test/codegen/fromcto/csharp/csharpvisitor.js, test/codegen/fromcto/data/model/hr.cto, test/codegen/fromcto/data/model/hr_base.cto, test/codegen/fromcto/protobuf/data/org.accordproject.protocol.v1_0_0-expected.proto, test/common/graph.js, types/lib/codegen/fromcto/graphql/graphqlvisitor.d.ts
- <ONE>
- <TWO>
- <ONE>
- <TWO>
=> test(codegen) update HR model to use multiple namespaces

lib/codegen/fromcto/avro/avrovisitor.js, test/codegen/__snapshots__/codegen.js.snap
```
record Company {
string name;
Address headquarters;
map<string> companyProperties;
map<Employee> employeeDirectory;
map<TShirtSizeType> employeeTShirtSizes;
map<Concept> employeeProfiles;
map<string> employeeSocialSecurityNumbers;
}
```
=> feat(map): Codegen for Avro IDL Target

lib/codegen/fromcto/vocabulary/vocabularyvisitor.js, package-lock.json, package.json, test/codegen/__snapshots__/codegen.js.snap, test/codegen/fromcto/vocabulary/vocabularyvisitor.js, types/lib/codegen/fromcto/golang/golangvisitor.d.ts, types/lib/codegen/fromcto/vocabulary/vocabularyvisitor.d.ts
- added visitor methods for map-declaration. map-key, map-value
- Issue #69
=> feat(vocabulary): vocab support for map in vocab auto generation

lib/codegen/fromcto/typescript/typescriptvisitor.js, test/codegen/fromcto/typescript/typescriptvisitor.js
Some client applications have a preference for union types over inheritance and subclasses (even inside TypeScript).
This change introduces a new parameter that lets the client application control which variant to use when generating TypeScript from Concerto.
- Adds `flattenSubclassesToUnion` parameter to the TypeScriptVisitor. The existing behaviour is still the default
For example, when `flattenSubclassesToUnion = true`, we generate the following code
```typescript
export interface IDecorator extends IConcept {
name: string;
arguments?: DecoratorLiteralUnion[];
location?: IRange;
}
```
instead of the default
```typescript
export interface IDecorator extends IConcept {
name: string;
arguments?: IDecoratorLiteral[];
location?: IRange;
}
```
=> feat(ts): add flattenSubclassesToUnion param

lib/codegen/fromcto/csharp/csharpvisitor.js, test/codegen/__snapshots__/codegen.js.snap, test/codegen/fromcto/csharp/csharpvisitor.js, types/lib/codegen/fromcto/csharp/csharpvisitor.d.ts, types/lib/codegen/fromcto/golang/golangvisitor.d.ts
=> feat(map): Extend supported Key Types for C# codegen

lib/codegen/fromcto/rust/rustvisitor.js, test/codegen/__snapshots__/codegen.js.snap, test/codegen/fromcto/rust/rustvisitor.js, test/codegen/fromcto/typescript/typescriptvisitor.js
Updates Rust code generation to include map types. This particular PR just updates types on top of #72 by @jonathan-casey , I can only fork the project.
```rust
pub mock_map: HashMap<String, String> = HashMap::new();
```
```rust
pub mock_map: HashMap<String, String> = HashMap::new();
```
```rust
pub mock_map: HashMap<DateTime<Utc>, Person> = HashMap::new();
```
- Pull Request #72
=> feat(map): codegen map rust

lib/common/graph.js, test/common/graph.js
- While visiting classDeclarations, while adding super type as a dependency edge, we also add the supertype as a vertex and the classDeclaration as its dependent type so that we can include derived types of the super types in tree after we get the connected graph
- <ONE>
- <TWO>
- Issue #56
=> bug(common): include derived types in dependency graph

lib/codegen/fromcto/vocabulary/vocabularyvisitor.js, test/codegen/fromcto/vocabulary/vocabularyvisitor.js
-  Added condition to return null if propertyName is a reserved system property name.
-  Added unit test to verify that vocabulary is not generated for system property name ("$identifier"). 
- [This](https://github.com/accordproject/concerto/issues/776) was the originally reported issue (in the [concerto](https://github.com/accordproject/concerto) repository).
=> fix(codegen): skip vocabulary generation for system property names and add test - I97

.github/workflows/build.yml, .github/workflows/publish.yml, lib/codegen/fromOpenApi/cto/openApiVisitor.js, package-lock.json, package.json, types/lib/codegen/fromcto/vocabulary/vocabularyvisitor.d.ts, webpack.config.js
1. Updates dependencies and enables source maps support for web pack.
2. Update module to use Node 18.
3. Update build to use Node 18 and 20.
=> chore: update deps and enable source maps

lib/codegen/fromcto/csharp/csharpvisitor.js, lib/codegen/fromcto/golang/golangvisitor.js, lib/codegen/fromcto/graphql/graphqlvisitor.js, lib/codegen/fromcto/jsonschema/jsonschemavisitor.js, lib/codegen/fromcto/jsonschema/recursionvisitor.js, lib/codegen/fromcto/rust/rustvisitor.js, lib/codegen/fromcto/typescript/typescriptvisitor.js, lib/codegen/fromcto/vocabulary/vocabularyvisitor.js, lib/common/util.js, package-lock.json, test/codegen/fromcto/graphql/graphqlvisitor.js, types/lib/common/util.d.ts, webpack.config.js
- <ONE>
- <TWO>
- <ONE>
- <TWO>
=> Ds webpack util

lib/codegen/fromJsonSchema/cto/jsonSchemaVisitor.js, package-lock.json, package.json, scripts/coverage.js, scripts/tag.js, scripts/timestamp.js
=> chore(deps): update concerto dependencies

lib/common/graph.js, test/common/graph.js
Adds an option to create a dependency graph. (Does not include references from supertypes to extending types).
The `ConcertoGraphVisitor` now optionally supports a parameter, `createDependencyGraph`, that if truthy stops the visitor from creating edges from supertypes to extending types.
- [ x Vital features and changes captured in unit and/or integration tests
=> feat(dependency graph): add option to create a dependency graph

lib/codegen/fromcto/csharp/csharpvisitor.js, lib/codegen/fromcto/java/javavisitor.js, package-lock.json, package.json, test/codegen/codegen.js, test/codegen/fromcto/csharp/csharpvisitor.js, test/codegen/fromcto/java/javavisitor.js
This PR would support the codegen for CSharp 
This PR depends uses the API which is recently added to the concerto-core via PR https://github.com/accordproject/concerto/pull/890 . Once this PR is merged to concerto-core the current Pr would be functional.
- https://github.com/accordproject/concerto/pull/890
=> feat(csharp,java): support aliasing imports

lib/common/diagramvisitor.js, lib/common/graph.js, test/codegen/__snapshots__/codegen.js.snap, test/codegen/fromcto/data/model/hr.cto, test/codegen/fromcto/data/model/hr_base.cto, test/codegen/fromcto/plantuml/plantumlvisitor.js, test/common/graph.js
- Add decorator type references on declarations and properties to the dependency graph.
=> feat(common): check dependecy in decorators

lib/common/diagramvisitor.js, lib/common/graph.js, test/codegen/fromcto/data/model/hr.cto, test/codegen/fromcto/plantuml/plantumlvisitor.js, test/common/graph.js
- <ONE> Avoid running `filewriter` when adding decorators to directed graph
- Pull Request #<[126](https://github.com/accordproject/concerto-codegen/pull/126)>
=> fix(filewriter): disable visitor from calling the file writer

package-lock.json, package.json
=> chore(deps): update concerto deps

lib/codegen/fromcto/odata/odatavisitor.js, lib/common/diagramvisitor.js, lib/common/graph.js, test/codegen/__snapshots__/codegen.js.snap, test/codegen/codegen.js, test/codegen/fromcto/data/model/hr.cto, test/codegen/fromcto/data/model/hr_base.cto, test/codegen/fromcto/plantuml/plantumlvisitor.js, test/common/__snapshots__/graph.js.snap, test/common/graph.js
Fixes a crash with the logic to add types referenced in decorators to the graph. Updates tests to prove it works.
- <ONE>
- <TWO>
- <ONE>
- <TWO>
=> fix(graph): add decorators that ref types to graph

package-lock.json, package.json, test/codegen/__snapshots__/codegen.js.snap, test/codegen/fromcto/data/model/hr.cto, test/common/__snapshots__/graph.js.snap
- update concerto-codegen deps
=> chore(deps): update concerto deps and remove failing decorator

package-lock.json, package.json, test/codegen/fromcto/typescript/tsconfig.json, test/codegen/fromcto/typescript/typescriptunions.js
Moves a unit test for Typescript type generation from @acccordproject/concerto-types to here, where it belongs.
- <ONE>
- <TWO>
- <ONE>
- <TWO>
=> test(typescript): move test for TS union codegen from concerto-types

package-lock.json, package.json, test/codegen/__snapshots__/codegen.js.snap, test/codegen/fromcto/data/model/hr.cto, test/codegen/fromcto/typescript/typescriptunions.js, test/common/__snapshots__/graph.js.snap
- Updates to use latest unstable concerto-core and verifies that we do not have any errors if decorators use undeclared types
- Typescript union test was modified to not use IDecorator as that type is now declared twice (once in concerto.decorator and once in meta model). 
=> fix(decorator): validation of decorators

lib/common/basevisitor.js, lib/common/diagramvisitor.js, lib/common/graph.js, test/codegen/__snapshots__/codegen.js.snap, test/codegen/fromcto/data/model/hr.cto, test/codegen/fromcto/plantuml/plantumlvisitor.js, test/common/__snapshots__/graph.js.snap, test/common/graph.js, types/lib/common/basevisitor.d.ts, types/lib/common/diagramvisitor.d.ts, types/lib/common/graph.d.ts
In creating a connected graph, we observe that the relationship between declarations and fields are not reflected as expected. Specifically, when a field has a decorator, the associated decorator is not included in the filtered model manager, leading to an error due to failed decorator validation.
This change add the edge to reflect the relationship between the parent declaration and it's fields.
=> fix(graph): add edge to map relationship between declarations and decorators on fields
