- package-lock.json
- package.json
Updates all Concerto main repo dependencies to latest version.
> fix(deps): update main Concerto repo packages to v3.9.1

- lib/codegen/fromcto/avro/avrovisitor.js
- lib/codegen/fromcto/csharp/csharpvisitor.js
- lib/codegen/fromcto/golang/golangvisitor.js
- lib/codegen/fromcto/graphql/graphqlvisitor.js
- lib/codegen/fromcto/java/javavisitor.js
- lib/codegen/fromcto/jsonschema/jsonschemavisitor.js
- lib/codegen/fromcto/loopback/loopbackvisitor.js
- lib/codegen/fromcto/odata/odatavisitor.js
- lib/codegen/fromcto/protobuf/protobufvisitor.js
- lib/codegen/fromcto/rust/rustvisitor.js
- lib/codegen/fromcto/typescript/typescriptvisitor.js
- lib/codegen/fromcto/vocabulary/vocabularyvisitor.js
- lib/codegen/fromcto/xmlschema/xmlschemavisitor.js
- lib/common/diagramvisitor.js
- lib/common/graph.js
- package-lock.json
- package.json
- test/codegen/__snapshots__/codegen.js.snap
- test/codegen/codegen.js
- test/codegen/fromcto/csharp/csharpvisitor.js
- test/codegen/fromcto/data/model/hr.cto
- test/codegen/fromcto/golang/golangvisitor.js
- test/codegen/fromcto/typescript/typescriptvisitor.js
- test/common/graph.js
- types/lib/codegen/fromcto/typescript/typescriptvisitor.d.ts
- types/lib/common/diagramvisitor.d.ts
- types/lib/common/graph.d.ts
```
public Dictionary<string, string> dictionary1 { get; set; };
public Dictionary<string, System.DateTime> dictionary2 { get; set; };
public Dictionary<string, Employee> dictionary3 { get; set; };
```
```
export type Map1 = Map<string, string>;
export type Map2 = Map<string, Date>;
export type Map3 = Map<string, IEmployee>;
```
Note: Key Type is generated as Type String across all supported Targets until ambiguity on `$class` property is resolved with consensus amongst core concerto maintainers.
> feat(map): codegen map type

- lib/codegen/fromcto/typescript/typescriptvisitor.js
- test/codegen/__snapshots__/codegen.js.snap
- test/codegen/fromcto/data/model/hr.cto
- test/codegen/fromcto/typescript/typescriptvisitor.js
> feat(map): Extend supported Key Types for Typescript codegen

- lib/codegen/fromcto/odata/odatavisitor.js
- test/codegen/__snapshots__/codegen.js.snap
- test/codegen/fromcto/odata/odatavisitor.js
```
<ComplexType Name="CompanyProperties">
<Property Name="Key" Type="Edm.String"/>
<Property Name="Value" Type="Edm.String"/>
</ComplexType>
<ComplexType Name="EmployeeLoginTimes">
<Property Name="Key" Type="Edm.String"/>
<Property Name="Value" Type="Edm.DateTimeOffset"/>
</ComplexType>
<ComplexType Name="EmployeeSocialSecurityNumbers">
<Property Name="Key" Type="Edm.String"/>
<Property Name="Value" Type="Edm.String"/>
</ComplexType>
<ComplexType Name="NextOfKin">
<Property Name="Key" Type="Edm.String"/>
<Property Name="Value" Type="Edm.String"/>
</ComplexType>
<ComplexType Name="EmployeeProfiles">
<Property Name="Key" Type="Edm.String"/>
<Property Name="Value" Type="concerto.Concept"/>
</ComplexType>
<ComplexType Name="EmployeeDirectory">
<Property Name="Key" Type="Edm.String"/> …
```
> feat(map): Codegen for OData Target 

- package-lock.json
- package.json
Updates Concerto dependencies to latest version (3.16.0).
> feat(deps): updated concerto deps to v3.16.0

- package-lock.json
- package.json
Updates Concerto dependencies to latest version (3.16.1).
> feat(deps): updated concerto deps to v3.16.1

- package-lock.json
- package.json
Updates Concerto version after https://github.com/accordproject/concerto/pull/794
- Issue https://github.com/accordproject/concerto/issues/785
- Pull Request https://github.com/accordproject/concerto/pull/794#pullrequestreview-1848784770
> chore(concerto): update dependency version

- package-lock.json
- package.json
Updates Concerto version after https://github.com/accordproject/concerto/pull/805
> chore(concerto): update version

- lib/codegen/fromcto/mermaid/mermaidvisitor.js
- lib/common/diagramvisitor.js
- test/codegen/__snapshots__/codegen.js.snap
Removed backticks from mermaid code
Fix - https://github.com/accordproject/concerto/issues/665
- <ONE>
- <TWO>
> Removed backticks from mermaid code

- package-lock.json
- webpack.config.js
- <ONE>
- <TWO>
- <ONE>
- <TWO>
> fix: do not ignore util from webpack

- package-lock.json
- package.json
Update the Concerto package versions to the latest version.
- Update the version of the Concerto dependencies
> chore(deps): updatge concerto to packages to latest version

- package-lock.json
- package.json
> chore(packages.json): update concerto packages

- package-lock.json
- package.json
> chore(packages): update concerto packages

- package-lock.json
- package.json
revert deps PR merge commits
- <ONE>
- <TWO>
- <ONE>
- <TWO>
> revert(deps): revert deps PR

- lib/common/graph.js
- Adds a null check to the graph visitor to check for null decorator arguments.
- <ONE>
- <TWO>
> fix(graph): check for null decorator arg

- package-lock.json
- package.json
Update concerto deps to `3.19.1`
> chore(deps): update concerto-deps

- package-lock.json
- package.json
Signed-off-by: muhammed-abdulkadir <muhammed.abdulkadir@docusign.com>
- fix vulnerabilities in deps
> fix(*): fix vulns deps

- package-lock.json
- package.json
Fix package lock. Drop back concerto libs to `3.19.6`
- <ONE>
- <TWO>
- <ONE>
- <TWO>
> fix(package.json): fix package lock json

- package-lock.json
- package.json
> chore(deps): update concerto deps 

- lib/codegen/fromcto/markdown/markdownvisitor.js
- package.json
- test/codegen/__snapshots__/codegen.js.snap
- test/codegen/codegen.js
- test/codegen/fromcto/data/model/hr.cto
Improves Markdown generation to include details about declarations including @description comments.
Sample output
> feat(markdown): improve generated documentation for models

- package-lock.json
- package.json
- test/codegen/__snapshots__/codegen.js.snap
- test/codegen/fromcto/data/model/hr_base.cto
* Updates the concerto version to 3.21.0
* Fixes one failing test
> chore(*): update concerto dependency

- package-lock.json
- package.json
- <ONE>
- <TWO>
- <ONE>
- <TWO>
> chore(pkg): update concerto deps

- package-lock.json
- package.json
- Update cocnerto packages to v3.24.0
> chore(*): update concerto versions
